[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/OpenBangla/riti.git"]
git = "https://github.com/OpenBangla/riti.git"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "../../../vendor/rust"
